### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by drs251** [lightingghost/sifreader#3]
Hi again, I just tried to install sifreader with pip, but unfortunately I got an error message:

```
FileNotFoundError: No such file or directory: '/private/var/folders/<etc.>/sifreader/readme.md'
```

The cause seems to be on line 8 in `setup.py`:
 ```
with open(os.path.join(CURRENT_DIR, 'readme.md'), encoding='utf-8') as f:
```

I'm not going to pretend that I know how setup.py works, however, [in a recent package of mine](https://pypi.org/project/pyRealParser/), I used these parameters for `setup()` (which I 'borrowed' from another package...), and they work fine for me:

```
long_description=open("README.md").read(),
long_description_content_type="text/markdown",
```

This also produces a nicer output on pypi, could be worth a try.

**Comment by lightingghost** [comment]
@drs251 Thanks for letting me know. I have tried to change the setup.py  according to your suggestion, but it does not work as well. I think the problem was on the python environment I have. (with a lower version of setuptools) I created a temporary work around that works for `pip install`. I will work on this issue next week.
